### ISSUE TITLE
Bug on WindowsPaths with wrong slashes

### ISSUE THREAD

**Issue by koryphaeesatara** [sebastianfeldmann/camino#2]
Hello, 

i use Windows and i use a tool which use your lib and while i debug i found a problem in your code. 

Example: The path is "C:/example/path/to/file/or/directory"
I don't know why the path have the wrong slashes ($argv[0]) but your code dont correct interpret.

Base::normalizeWindows should be return true but it return false. 

https://github.com/sebastianfeldmann/camino/blob/a4d677f06df7c9479b4176dcd1d6dc2115c940bb/src/Path/Base.php#L111

Thanks

P.S. Sorry for my bad english

**Comment by sebastianfeldmann** [comment]
Thanks for reporting this issue

It should be fixed in version 0.9.3

I added a unit test testing a forward slash windows path and that works. If you still have any issues feel free to reopen this issue.
